### ISSUE TITLE
Full FPDS link is confusing

### ISSUE THREAD

**Issue by gbinal** [presidential-innovation-fellows/apps-gov#93]
For each app, where there's a list of agency customers, there's a parentical mention after that says: `(full FPDS list here)`, that goes to the [FPDS homepage](https://www.fpds.gov/fpdsng_cms/index.php/en/).  

I might be missing something but that seems pretty confusing and unhelpful.  I'd instead expect something directly relevant, either to more info on those agencies that are users or to something like the full list of potential agency users.  

![screen shot 2016-03-16 at 9 11 56 pm](https://cloud.githubusercontent.com/assets/633088/13833379/cb23c436-ebbb-11e5-8397-75fe26556598.png)

**Comment by stroupaloop** [comment]
Hm, not sure the latter is possible since we don't know which agencies are 'able' to procure a given product as that's a decision on a case by case basis. We could request the products to list additional information on the contracts they currently have, but when discussing this are concerned it steps too far into a competitive sales advantage for them.

I'm happy to take it down if it's not useful, but the intent during our discussions was to at least supplement this list with the location to find information on all gov contracts.

**Comment by ajb** [comment]
I assume "confusing and unhelpful" describes a government user, correct?

The flipside of this issue is that as a company that's listing an app, I'd like a way to list case studies and/or URIs that show our app is _loved_ by its USG users.

I'd prefer to not go off FPDS as a source of "truth" since there's a lot of procurement methods that won't show up on there. The competitive advantage stuff is absolute BS.

**Comment by stroupaloop** [comment]
Thanks for the feedback, we'll take it down for now and figure out alternative ways for gov buyers to explore all contracts (I know 18F is working on some initiatives here)

**Comment by stroupaloop** [comment]
fixed cb623fe
